# Generated by Django 5.0.6 on 2024-06-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listhelper', '0002_checklist_alter_checklistitem_relatedfile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistHasChacklistItem',
            new_name='ChecklistHasChecklistItem',
        ),
    ]
